name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag alexisgeoffrey/aoe4elobot:$(date +%s) && docker push docker push alexisgeoffrey/aoe4elobot:$(date +%s)
